### ISSUE TITLE
[Android] [FIL] Exception occurs when sending Filecoin (Mainnet) from Trust Wallet

### ISSUE THREAD

**Issue by pradysp** [trustwallet/wallet-core#1162]
**Bug Description:**
User is unable to send any Filecoin (FIL) Mainnet coins from **Android Trust Wallet app** as Exception is received

**To reproduce the behavior, please follow the steps:**
Steps:
1. Receive Filecoin (FIL) on Android Trust Wallet app
2. Now Click Send
3. Enter a valid FIL mainnet address as recipient 
4. Enter Amount and press Continue
5. Observe the error '**IllegalStateException**' in Confirm Transaction screen (see attached screenshot)

**Expected behavior:**
User should be able to send FIL coins to a valid address without any exception or error. Now user is unable to send FIL coins from their android wallet.

**Screenshots:**
Please see attached screenshot
([url](url
![FIL_screenshot](https://user-images.githubusercontent.com/36413781/98719862-4e52c780-23b6-11eb-90d2-ff755822ef2e.jpg)
))

**Additional context**
_Full error message Text for reference_: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 35 path $.errror
TRY AGAIN

**Comment by hewigovens** [comment]
What is the android app version?

**Comment by pradysp** [comment]
@hewigovens Issue is present since Filecoin (FIL) was added to Trustwalelt. Last seen at Android app version **1.21.6**
Also, the Incoming Filecoin txn history is not shown but FIL balance is reflected correctly. Maybe this is causing the issue in sending out the existing balance. Please investigate, thanks

FYI @terorie

**Comment by vcoolish** [comment]
@pradysp 
Will be fixed in next Android release

**Comment by hewigovens** [comment]
@pradysp should be fixed in new Android version, could you please try? close for now

**Comment by pradysp** [comment]
@hewigovens The fix is not yet available. Since the last comment from @vcoolish , no new Android wallet version has been released to the play store yet. Suggest you keep this open, I will verify after the fixed version is available to test, then will close if it is actually fixed.

**Comment by vcoolish** [comment]
Latest version is 1.22.8
Should be already available to 80% users at least

**Comment by hewigovens** [comment]
@pradysp can you try version 1.22.8?

**Comment by pradysp** [comment]
@hewigovens I'm still seeing 1.21.6 in my Play Store. Not sure why its not updated to the latest. Will verify soon as I see it.
FYI @vcoolish

**Comment by vcoolish** [comment]
Should be available now.

**Comment by pradysp** [comment]
FIL Mainnet Exception issue when sending coin has been fixed in Android version 1.22.9 . Hence closing the bug.

Thanks @vcoolish  @hewigovens
